# Generated by Django 6.0.3 on 2026-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiryform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('general', 'General inquiry'), ('scholarship', 'Scholarship'), ('agriculture', 'Agriculture'), ('infrastructure', 'Infrastructure'), ('complaint', 'Complaint')], max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
