# Generated by Django 6.0.3 on 2026-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(choices=[('jan_feb', 'January / February'), ('feb_mar', 'February / March'), ('aug_sep', 'August / September')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='festivals/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
